sticker = [
    'CAACAgIAAxkBAAIQ3WKzjZnLXGqPq3WWmA4hEDBKjPY-AAIeGgACx9mQSZAzjAbMofnnKQQ',
    'CAACAgIAAxkBAAIQ32KzjZxowAobJMYLec7N1GJHJA6nAAJ-HgACW2ORSctDKfIEK3aVKQQ',
    'CAACAgIAAxkBAAIQ4WKzjZ4y2Hnp4GUxdtesL-FUzSRnAAKSGwACPNSQScgNJfgNwbUeKQQ',
    'CAACAgIAAxkBAAIQ42KzjaDmfLYXsQadHzaiVLPOcc7EAAJ0FgACphKQSf98WM4eBQZxKQQ',
    'CAACAgIAAxkBAAIQ5WKzjaJChA7mc63HGgV7pjmECZVyAALSGAAChb-RSdoql0A2m0MzKQQ',
    'CAACAgIAAxkBAAIQ52KzjaQVpw0Z73K7rJBUg76C3YlxAAI5GwACbSyQSfeQmDAmkwZHKQQ',
    'CAACAgIAAxkBAAIQ6WKzjae4dd7_orgDQHcdV7XdzM3IAAIMGQACCreRSc1awY-Y2nXaKQQ',
    'CAACAgIAAxkBAAIQ62Kzjald4m5wKiRHz2TQC3IMvEr2AAI4GQACFkyISSo6jPEGLCveKQQ',
    'CAACAgIAAxkBAAIQ7WKzjawagkmaQkD2fOcHPkeyO6f9AAJFHgACBkCRSaoF_JFmf_DbKQQ',
    'CAACAgIAAxkBAAIQ72Kzja6mzen_HBo16KWpm9QzpPEbAAJkFgACsiqISarwminEk5i_KQQ',
    'CAACAgIAAxkBAAIQ8WKzjbCo3WtSoUzePlk08fnr1UWbAAJ3GwACWUqJSeBK7hkn4rYAASkE',
    'CAACAgIAAxkBAAIQ82KzjbKxrgAB-aceAyO5HFcHsyRKpAAC-RgAAtW5iUlPA9tmY_ZkSSkE',
    'CAACAgIAAxkBAAIQ9WKzjbSiNfrRvLpotR6jpnX5GzkLAAJHHAACWbeQSUHSkFKoXUS1KQQ',
    'CAACAgIAAxkBAAIQ92KzjbejEMfhJkQEwuLGF64rcJTQAALuHAACSuCRSW4DsYNDfxwzKQQ',
    'CAACAgIAAxkBAAIQ-WKzjboTsf9sdoOkYh8lUMafmswRAAKzGAACdW2QSRQm1l9jCB41KQQ'
]